import 'package:flutter/material.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'package:learn_tagalog/custom/alphabet_letters_icons.dart';
import 'package:learn_tagalog/custom/days_icons_icons.dart';
import 'package:learn_tagalog/models/lesson.dart';
import 'package:learn_tagalog/models/lesson_content.dart';
import 'package:learn_tagalog/models/topic.dart';
import 'package:learn_tagalog/custom/months_icon_icons.dart';
import 'package:learn_tagalog/custom/number_icons_icons.dart';

class Utils {
  static List<Topic> getMockedCategories() {
    return [
      Topic(
        name: 'Alphabet',
        icon: FontAwesomeIcons.wordpress,
        color: Color.fromRGBO(124, 180, 2, 1.0),
        backgroundColor: Color.fromRGBO(171, 236, 49, 1.0),
        lessons: [
          Lesson(
              name: 'Alphabet One',
              icon: FontAwesomeIcons.pencilAlt,
              color: Color.fromRGBO(124, 180, 2, 1.0),
              backgroundColor: Color.fromRGBO(171, 236, 49, 1.0),
              difficulty: 'Easy',
              lessonContent: [
                LessonContent(
                  tagalogWord: 'Ah',
                  engWord: 'A',
                  icon: AlphabetLetters.alpha_a,
                  audio: 'assets/audio/alphabet/Ah.mp3',
                  color: Colors.yellow,
                  type: 'letter',
                ),
                LessonContent(
                  tagalogWord: 'Ba',
                  engWord: 'B',
                  icon: AlphabetLetters.alpha_b,
                  audio: 'assets/audio/alphabet/Ba.mp3',
                  color: Colors.yellow,
                  type: 'letter',
                ),
                LessonContent(
                  tagalogWord: 'Ka',
                  engWord: 'C',
                  icon: AlphabetLetters.alpha_c,
                  audio: 'assets/audio/alphabet/Ka.mp3',
                  color: Colors.yellow,
                  type: 'letter',
                ),
                LessonContent(
                  tagalogWord: 'Da',
                  engWord: 'D',
                  icon: AlphabetLetters.alpha_d,
                  audio: 'assets/audio/alphabet/Da.mp3',
                  color: Colors.yellow,
                  type: 'letter',
                ),
                LessonContent(
                  tagalogWord: 'Eh',
                  engWord: 'E',
                  icon: AlphabetLetters.alpha_e,
                  audio: 'assets/audio/alphabet/Eh.mp3',
                  color: Colors.yellow,
                  type: 'letter',
                ),
                LessonContent(
                  tagalogWord: 'Ga',
                  engWord: 'G',
                  icon: AlphabetLetters.alpha_g,
                  audio: 'assets/audio/alphabet/Ga.mp3',
                  color: Colors.yellow,
                  type: 'letter',
                ),
                LessonContent(
                  tagalogWord: 'Ha',
                  engWord: 'H',
                  icon: AlphabetLetters.alpha_h,
                  audio: 'assets/audio/alphabet/Ha.mp3',
                  color: Colors.yellow,
                  type: 'letter',
                ),
                LessonContent(
                  tagalogWord: 'e',
                  engWord: 'I',
                  icon: AlphabetLetters.alpha_i,
                  audio: 'assets/audio/alphabet/E.mp3',
                  color: Colors.yellow,
                  type: 'letter',
                ),
                LessonContent(
                  tagalogWord: 'La',
                  engWord: 'L',
                  icon: AlphabetLetters.alpha_l,
                  audio: 'assets/audio/alphabet/La.mp3',
                  color: Colors.yellow,
                  type: 'letter',
                ),
                LessonContent(
                  tagalogWord: 'Ma',
                  engWord: 'M',
                  icon: AlphabetLetters.alpha_m,
                  audio: 'assets/audio/alphabet/Ma.mp3',
                  color: Colors.yellow,
                  type: 'letter',
                )
              ],),
          Lesson(
              name: 'Alphabet Two',
              icon: FontAwesomeIcons.bookOpen,
              color: Color.fromRGBO(124, 180, 2, 1.0),
              backgroundColor: Color.fromRGBO(171, 236, 49, 1.0),
              difficulty: 'Easy',
              lessonContent: [
                LessonContent(
                    tagalogWord: 'Na',
                    engWord: 'N',
                    icon: AlphabetLetters.alpha_n,
                    audio: 'assets/audio/alphabet/Na.mp3',
                    color: Colors.yellow,
                    type: 'word',),
                LessonContent(
                    tagalogWord: 'Oh',
                    engWord: 'O',
                    icon: AlphabetLetters.alpha_o,
                    audio: 'assets/audio/alphabet/Oh.mp3',
                    color: Colors.yellow,
                    type: 'word',),
                LessonContent(
                    tagalogWord: 'Pah',
                    engWord: 'P',
                    icon: AlphabetLetters.alpha_p,
                    audio: 'assets/audio/alphabet/Pa.mp3',
                    color: Colors.yellow,
                    type: 'word',),
                LessonContent(
                    tagalogWord: 'Ra',
                    engWord: 'R',
                    icon: AlphabetLetters.alpha_r,
                    audio: 'assets/audio/alphabet/Ra.mp3',
                    color: Colors.yellow,
                    type: 'word',),
                LessonContent(
                    tagalogWord: 'Sa',
                    engWord: 'S',
                    icon: AlphabetLetters.alpha_s,
                    audio: 'assets/audio/alphabet/Sa.mp3',
                    color: Colors.yellow,
                    type: 'word',),
                LessonContent(
                    tagalogWord: 'Ta',
                    engWord: 'T',
                    icon: AlphabetLetters.alpha_t,
                    audio: 'assets/audio/alphabet/Ta.mp3',
                    color: Colors.yellow,
                    type: 'word',),
                LessonContent(
                    tagalogWord: 'Ooh',
                    engWord: 'U',
                    icon: AlphabetLetters.alpha_u,
                    audio: 'assets/audio/alphabet/ooh.mp3',
                    color: Colors.yellow,
                    type: 'word',),
                LessonContent(
                    tagalogWord: 'Wa',
                    engWord: 'W',
                    icon: AlphabetLetters.alpha_w,
                    audio: 'assets/audio/alphabet/wah.mp3',
                    color: Colors.yellow,
                    type: 'word',),
                LessonContent(
                    tagalogWord: 'Ya',
                    engWord: 'Y',
                    icon: AlphabetLetters.alpha_y,
                    audio: 'assets/audio/alphabet/Ya.mp3',
                    color: Colors.yellow,
                    type: 'word')
              ]),
        ],
      ),
      Topic(
        name: 'Numbers',
        icon: FontAwesomeIcons.personBooth,
        color: Color.fromRGBO(0, 149, 85, 1.0),
        backgroundColor: Colors.green[400],
        lessons: [
          Lesson(
              name: 'Numbers One',
              icon: FontAwesomeIcons.sortAmountUp,
              color: Color.fromRGBO(0, 149, 85, 1.0),
              backgroundColor: Colors.green[400],
              difficulty: 'Easy',
              lessonContent: [
                LessonContent(
                  tagalogWord: 'Isa',
                  engWord: 'One',
                  icon: FontAwesomeIcons.diceOne,
                  color: Colors.white,
                  audio: 'assets/audio/numbers/Isa.mp3',
                  type: 'word',
                ),
                LessonContent(
                  tagalogWord: 'Daliwa',
                  engWord: 'Two',
                  icon: FontAwesomeIcons.diceTwo,
                  color: Colors.white,
                  audio: 'assets/audio/numbers/Daliwa.mp3',
                  type: 'word',
                ),
                LessonContent(
                  tagalogWord: 'Tatlo',
                  engWord: 'Three',
                  icon: FontAwesomeIcons.diceThree,
                  color: Colors.white,
                  audio: 'assets/audio/numbers/Tatlo.mp3',
                  type: 'word',
                ),
                LessonContent(
                  tagalogWord: 'Apat',
                  engWord: 'Four',
                  icon: FontAwesomeIcons.diceFour,
                  color: Colors.white,
                  audio: 'assets/audio/numbers/Apat.mp3',
                  type: 'word',
                ),
                LessonContent(
                  tagalogWord: 'Lima',
                  engWord: 'Five',
                  icon: FontAwesomeIcons.diceFive,
                  color: Colors.white,
                  audio: 'assets/audio/numbers/Lima.mp3',
                  type: 'word',
                ),
                LessonContent(
                  tagalogWord: 'Anim',
                  engWord: 'Six',
                  icon: FontAwesomeIcons.diceSix,
                  color: Colors.white,
                  audio: 'assets/audio/numbers/Anim.mp3',
                  type: 'word',
                ),
                LessonContent(
                  tagalogWord: 'Pito',
                  engWord: 'Seven',
                  icon: Icons.seven_mp,
                  color: Colors.green,
                  audio: 'assets/audio/numbers/Pito.mp3',
                  type: 'word',
                ),
                LessonContent(
                  tagalogWord: 'Walo',
                  engWord: 'Eight',
                  icon: Icons.eight_mp,
                  color: Colors.white,
                  audio: 'assets/audio/numbers/Walo.mp3',
                  type: 'word',
                ),
                LessonContent(
                  tagalogWord: 'Siyam',
                  engWord: 'Nine',
                  icon: Icons.nine_mp,
                  color: Colors.blue,
                  audio: 'assets/audio/numbers/Siyam.mp3',
                  type: 'word',
                ),
                LessonContent(
                  tagalogWord: 'Sampu',
                  engWord: 'Ten',
                  icon: Icons.ten_mp,
                  color: Colors.white,
                  audio: 'assets/audio/numbers/Sampu.mp3',
                  type: 'word',
                )
              ]),
          Lesson(
            name: 'Numbers Two',
            icon: FontAwesomeIcons.listOl,
            color: Color.fromRGBO(0, 149, 85, 1.0),
            backgroundColor: Colors.green[400],
            difficulty: 'Easy',
            lessonContent: [
              LessonContent(
                tagalogWord: 'Zero',
                engWord: 'Zero',
                icon: Icons.exposure_zero,
                color: Colors.white,
                audio: 'assets/audio/numbers/zero.mp3',
                type: 'word',
              ),
              LessonContent(
                tagalogWord: 'Sampu',
                engWord: 'Ten',
                icon: Icons.ten_mp,
                color: Colors.white,
                audio: 'assets/audio/numbers/Sampu.mp3',
                type: 'word',
              ),
              LessonContent(
                tagalogWord: 'Bente',
                engWord: 'Twenty',
                icon: Icons.twenty_mp,
                color: Colors.white,
                audio: 'assets/audio/numbers/Bente.mp3',
                type: 'word',
              ),
              LessonContent(
                tagalogWord: 'Tatlong Ko',
                engWord: 'Thirty',
                icon: NumberIcons.thirty,
                color: Colors.white,
                audio: 'assets/audio/numbers/Tatlong Ko.mp3',
                type: 'word',
              ),
              LessonContent(
                tagalogWord: 'Apatnapu',
                engWord: 'Forty',
                icon: NumberIcons.forty,
                color: Colors.white,
                audio: 'assets/audio/numbers/Apatnapu.mp3',
                type: 'word',
              ),
              LessonContent(
                tagalogWord: 'Limango',
                engWord: 'Fifty',
                icon: NumberIcons.fifty,
                color: Colors.white,
                audio: 'assets/audio/numbers/Limango.mp3',
                type: 'word',
              ),
              LessonContent(
                tagalogWord: 'Animnapo',
                engWord: 'Sixty',
                icon: NumberIcons.sixty,
                color: Colors.white,
                audio: 'assets/audio/numbers/Animnapo.mp3',
                type: 'word',
              ),
              LessonContent(
                tagalogWord: 'Pitungpo',
                engWord: 'Seventy',
                icon: NumberIcons.birthday,
                color: Colors.white,
                audio: 'assets/audio/numbers/Pitungpo.mp3',
                type: 'word',
              ),
              LessonContent(
                tagalogWord: 'Walungpo',
                engWord: 'Eighty',
                icon: NumberIcons.eighty,
                color: Colors.white,
                audio: 'assets/audio/numbers/Walungpo.mp3',
                type: 'word',
              ),
              LessonContent(
                tagalogWord: 'Siyamnapo',
                engWord: 'Ninety',
                icon: NumberIcons.ninety,
                color: Colors.white,
                audio: 'assets/audio/numbers/Siyamnapo.mp3',
                type: 'word',
              ),
              LessonContent(
                tagalogWord: 'Isang Daan',
                engWord: 'One Hundred',
                icon: Icons.money,
                color: Colors.green,
                audio: 'assets/audio/numbers/Isang Daan.mp3',
                type: 'word',
              ),
              LessonContent(
                tagalogWord: 'Isang Libo',
                engWord: 'One thousand',
                icon: Icons.one_k,
                color: Colors.white,
                audio: 'assets/audio/numbers/Isang Libo.mp3',
                type: 'word',
              ),
            ],
          ),
          Lesson(
              name: 'Numbers Three',
              icon: FontAwesomeIcons.calculator,
              color: Color.fromRGBO(0, 149, 85, 1.0),
              backgroundColor: Colors.green[400],
              difficulty: 'Medium',
              lessonContent: [
                LessonContent(
                  tagalogWord: 'Isang saging',
                  engWord: 'a banana',
                  icon: FontAwesomeIcons.carrot,
                  color: Colors.yellow,
                  audio: 'assets/audio/numbers/Isang saging.mp3',
                  type: 'phrase',
                ),
                LessonContent(
                  tagalogWord: 'Dalawang orange',
                  engWord: 'Two oranges',
                  icon: FontAwesomeIcons.solidLemon,
                  color: Colors.orange,
                  audio: 'assets/audio/numbers/Dalawang orange.mp3',
                  type: 'phrase',
                ),
                LessonContent(
                  tagalogWord: 'Tatlong mansanas',
                  engWord: 'Three apples',
                  icon: FontAwesomeIcons.apple,
                  color: Colors.red,
                  audio: 'assets/audio/numbers/Tatlong mansanas.mp3',
                  type: 'phrase',
                ),
                LessonContent(
                  tagalogWord: 'Apat na tao',
                  engWord: 'Four people',
                  icon: Icons.group_rounded,
                  color: Colors.green,
                  audio: 'assets/audio/numbers/Apat na tao.mp3',
                  type: 'phrase',
                ),
                LessonContent(
                  tagalogWord: 'Limang pusa',
                  engWord: 'Five cats',
                  icon: FontAwesomeIcons.cat,
                  color: Colors.white,
                  audio: 'assets/audio/numbers/Limang pusa.mp3',
                  type: 'phrase',
                ),
                LessonContent(
                  tagalogWord: 'Anim na aso',
                  engWord: 'Six dogs',
                  icon: FontAwesomeIcons.dog,
                  color: Colors.brown,
                  audio: 'assets/audio/numbers/Anim na aso.mp3',
                  type: 'phrase',
                ),
                LessonContent(
                  tagalogWord: 'Itong tao',
                  engWord: 'Seven people',
                  icon: Icons.seven_mp,
                  color: Colors.white,
                  audio: 'assets/audio/numbers/Itong tao.mp3',
                  type: 'phrase',
                ),
                LessonContent(
                  tagalogWord: 'Walong pirasong tsokolate',
                  engWord: 'Eight pieces of chocolate',
                  icon: Icons.seven_mp,
                  color: Colors.white,
                  audio: 'assets/audio/walong pirasong tsokolate.mp3',
                  type: 'phrase',
                ),
                LessonContent(
                  tagalogWord: 'Siyam na kotse',
                  engWord: 'Nine cars',
                  icon: Icons.car_repair,
                  color: Colors.white,
                  audio: 'assets/audio/numbers/Siyam na kotse.mp3',
                  type: 'phrase',
                ),
                LessonContent(
                  tagalogWord: 'Sampung aso',
                  engWord: 'Ten dogs',
                  icon: FontAwesomeIcons.dog,
                  color: Colors.white,
                  audio: 'assets/audio/numbers/Sampung aso.mp3',
                  type: 'phrase',
                ),
              ]),
          Lesson(
              name: 'Numbers Four',
              icon: FontAwesomeIcons.sortNumericDown,
              color: Color.fromRGBO(0, 149, 85, 1.0),
              backgroundColor: Colors.green[400],
              difficulty: 'Medium',
              lessonContent: [
                LessonContent(
                  tagalogWord: 'Labing isang itik',
                  engWord: 'Eleven ducks',
                  icon: Icons.seven_mp,
                  color: Colors.white,
                  audio: 'assets/audio/numbers/Labing isang itik.mp3',
                  type: 'phrase',
                ),
                LessonContent(
                  tagalogWord: 'Dalawangput anim na tao',
                  engWord: 'Twenty Six people',
                  icon: Icons.seven_mp,
                  color: Colors.white,
                  audio: 'assets/audio/numbers/Dalawangput anim na tao.mp3',
                  type: 'phrase',
                ),
                LessonContent(
                  tagalogWord: 'Tatlumpu\'t siyam na taong gulang',
                  engWord: '39 years old',
                  icon: Icons.seven_mp,
                  color: Colors.white,
                  audio: 'assets/audio/numbers/tatlumpu\'t siyam na taong gulang.mp3',
                  type: 'phrase',
                ),
                LessonContent(
                  tagalogWord: 'Apat na pu’t tatlo ng lapis',
                  engWord: 'Forty three pencils',
                  icon: Icons.seven_mp,
                  color: Colors.white,
                  audio: 'assets/audio/numbers/Apat na pu\'t tatlo ng lapis.mp3',
                  type: 'phrase',
                ),
                LessonContent(
                  tagalogWord: 'Limang pu\'t limang pahina',
                  engWord: 'Fifty five pages',
                  icon: Icons.seven_mp,
                  color: Colors.white,
                  audio: 'assets/audio/numbers/Limang pu\'t limang pahina.mp3',
                  type: 'phrase',
                ),
                LessonContent(
                  tagalogWord: 'Anim na salita',
                  engWord: 'Six words',
                  icon: Icons.seven_mp,
                  color: Colors.white,
                  audio: 'assets/audio/numbers/Anim na salita.mp3',
                  type: 'phrase',
                ),
                LessonContent(
                  tagalogWord: 'Pitong pu\'t apat na taong gulang',
                  engWord: '74 years old',
                  icon: Icons.seven_mp,
                  color: Colors.white,
                  audio: 'assets/audio/numbers/Pitong pu\'t apat na taong gulang.mp3',
                  type: 'phrase',
                ),
                LessonContent(
                  tagalogWord: 'Walongput tatlong taon na nakaraan',
                  engWord: '83 years old',
                  icon: Icons.seven_mp,
                  color: Colors.white,
                  audio: 'assets/audio/numbers/Walongput tatlong taon na nakaraan.mp3',
                  type: 'phrase',
                ),
                LessonContent(
                  tagalogWord: 'Siyamnaput walong tao',
                  engWord: '98 people',
                  icon: Icons.seven_mp,
                  color: Colors.white,
                  audio: 'assets/audio/Siyamnaput walong tao.mp3',
                  type: 'phrase',
                ),
                LessonContent(
                  tagalogWord: 'Isang Daan at apat na pung salita',
                  engWord: '140 pages',
                  icon: Icons.book,
                  color: Colors.white,
                  audio: 'assets/audio/numbers/Isang Daan at apat na pung salita.mp3',
                  type: 'phrase',
                ),
              ]),
          Lesson(
            name: 'Numbers Five',
            icon: FontAwesomeIcons.pencilRuler,
            color: Color.fromRGBO(0, 149, 85, 1.0),
            backgroundColor: Colors.green[400],
            difficulty: 'Hard',
            lessonContent: [
              LessonContent(
                tagalogWord: 'Si Megan ay dalawang pusa',
                engWord: 'Megan has 2 cats',
                icon: FontAwesomeIcons.cat,
                color: Colors.white,
                audio: 'assets/audio/numbers/Si Megan ay dalawang pusa.mp3',
                type: 'phrase',
              ),
              LessonContent(
                tagalogWord: 'Si Amber ay may tatlong crayola',
                engWord: 'Amber has 3 crayons',
                icon: FontAwesomeIcons.pencilAlt,
                color: Colors.yellow,
                audio: 'assets/audio/numbers/Si Amber ay may tatlong crayola.mp3',
                type: 'phrase',
              ),
              LessonContent(
                tagalogWord: 'May limang piso si Max',
                engWord: 'Max has 5 pesos',
                icon: Icons.attach_money,
                color: Colors.white,
                audio: 'assets/audio/numbers/May limang piso si Max.mp3',
                type: 'phrase',
              ),
              LessonContent(
                tagalogWord: 'Si Ronald ay limampu\'t limang taong gulang',
                engWord: 'Ronald is 55 years old',
                icon: Icons.cake,
                color: Colors.white,
                audio:
                    'assets/audio/numbers/Si Ronald ay limampu\'t limang taong gulang.mp3',
                type: 'phrase',
              ),
              LessonContent(
                tagalogWord: 'Ako ay may tatlong pusa at isang aso',
                engWord: 'I have 3 cats and one dog',
                icon: Icons.pets,
                color: Colors.grey,
                audio: 'assets/audio/numbers/Ako ay may tatlong pusa at isang aso.mp3',
                type: 'phrase',
              ),
              LessonContent(
                tagalogWord: 'Ako ay apat na put daliwang golang',
                engWord: 'I am 42 years old',
                icon: Icons.person,
                color: Colors.white,
                audio: 'assets/audio/numbers/Ako ay apat na put daliwang golang.mp3',
                type: 'phrase',
              ),
              LessonContent(
                tagalogWord: 'Si David ay may dalawang asukal sa kape niya',
                engWord: 'David has 2 sugars in his coffee',
                icon: Icons.local_cafe,
                color: Colors.white,
                audio:
                    'assets/audio/numbers/Si David ay may dalawang asukal sa kape niya.mp3',
                type: 'phrase',
              ),
              LessonContent(
                tagalogWord: 'Si Alicia ay may isang kapatid na babae',
                engWord: 'Alicia has one sister',
                icon: FontAwesomeIcons.female,
                color: Colors.white,
                audio:
                    'assets/audio/numbers/Si Alicia ay may isang kapatid na babae.mp3',
                type: 'phrase',
              ),
              LessonContent(
                tagalogWord: 'Si Jennifer ay may apat na kapatid na lalaki',
                engWord: 'Jennifer has 4 brothers',
                icon: FontAwesomeIcons.male,
                color: Colors.white,
                audio:
                    'assets/audio/numbers/Si Jennifer ay may apat na kapatid na lalaki.mp3',
                type: 'phrase',
              ),
              LessonContent(
                tagalogWord: 'Ang nanay ko ay tatlongput limang taong gulang',
                engWord: 'My mother is 35 years old',
                icon: Icons.person_sharp,
                color: Colors.white,
                audio:
                    'assets/audio/numbers/Ang nanay ko ay tatlongput limang taong gulang.mp3',
                type: 'phrase',
              )
            ],
          ),
        ],
      ),
      Topic(
        name: 'Days of the Week',
        icon: FontAwesomeIcons.plane,
        color: Colors.red[700],
        backgroundColor: Colors.redAccent,
        lessons: [
          Lesson(
              name: 'Days One',
              icon: FontAwesomeIcons.bicycle,
              color: Colors.red[700],
              backgroundColor: Colors.redAccent,
              difficulty: 'Easy',
              lessonContent: [
                LessonContent(
                    tagalogWord: 'Lunes',
                    engWord: 'Monday',
                    color: Colors.orange,
                    icon: DaysIcons.monday_calendar_page,
                    audio: 'assets/audio/days_of_the_week/Lunes.mp3',
                    type: 'word'),
                LessonContent(
                    tagalogWord: 'Martes',
                    engWord: 'Tuesday',
                    color: Colors.orange,
                    icon: DaysIcons.tuesday_daily_calendar_page,
                    audio: 'assets/audio/days_of_the_week/Martes.mp3',
                    type: 'word'),
                LessonContent(
                    tagalogWord: 'Miyerkules',
                    engWord: 'Wednesday',
                    color: Colors.orange,
                    icon: DaysIcons.wednesday_calendar_daily_page,
                    audio: 'assets/audio/days_of_the_week/Miyerkules.mp3',
                    type: 'word'),
                LessonContent(
                    tagalogWord: 'Huwebes',
                    engWord: 'Thursday',
                    color: Colors.orange,
                    icon: DaysIcons
                        .thursday_calendar_daily_page_interface_symbol,
                    audio: 'assets/audio/days_of_the_week/Huwebes.mp3',
                    type: 'word'),
                LessonContent(
                    tagalogWord: 'Biyernes',
                    engWord: 'Friday',
                    color: Colors.orange,
                    icon: DaysIcons.friday_daily_calendar_page,
                    audio: 'assets/audio/days_of_the_week/Biyernes.mp3',
                    type: 'word'),
                LessonContent(
                    tagalogWord: 'Sabado',
                    engWord: 'Saturday',
                    color: Colors.orange,
                    icon: DaysIcons
                        .saturday_calendar_daily_page_interface_symbol,
                    audio: 'assets/audio/days_of_the_week/Sabado.mp3',
                    type: 'word'),
                LessonContent(
                    tagalogWord: 'Linggo',
                    engWord: 'Sunday',
                    color: Colors.orange,
                    icon: DaysIcons.sunday_daily_calendar_page,
                    audio: 'assets/audio/days_of_the_week/Linggo.mp3',
                    type: 'word'),
              ]),
          Lesson(
              name: 'Days Two',
              icon: FontAwesomeIcons.tractor,
              color: Colors.red[700],
              backgroundColor: Colors.redAccent,
              difficulty: 'Medium',
              lessonContent: [
                LessonContent(
                    tagalogWord: 'Ngayon ay Lunes',
                    engWord: 'Today is Monday',
                    color: Colors.orange,
                    icon: DaysIcons.monday_calendar_page,
                    audio: 'assets/audio/days_of_the_week/Ngayun ay Lunes.mp3',
                    type: 'phrase'),
                LessonContent(
                    tagalogWord: 'Bukas ay Miyerkules',
                    engWord: 'Tomorrow',
                    color: Colors.orange,
                    icon: DaysIcons.tuesday_daily_calendar_page,
                    audio: 'assets/audio/days_of_the_week/Bukas ay Miyerkules.mp3',
                    type: 'phrase'),
                LessonContent(
                    tagalogWord: 'Ngayon ay Huwebes',
                    engWord: 'Today is Thursday',
                    color: Colors.orange,
                    icon: DaysIcons.thursday_calendar_daily_page_interface_symbol,
                    audio: 'assets/audio/days_of_the_week/Ngayon ay Huwebes.mp3',
                    type: 'phrase'),
                LessonContent(
                    tagalogWord: 'Ngayon ay Biyernes',
                    engWord: 'Today is Friday',
                    color: Colors.orange,
                    icon: DaysIcons
                        .friday_daily_calendar_page,
                    audio: 'assets/audio/days_of_the_week/Ngayon ay Biyernes.mp3',
                    type: 'phrase'),
                LessonContent(
                    tagalogWord: 'Bukas ay Sabado',
                    engWord: 'Tomorrow is Saturday',
                    color: Colors.orange,
                    icon: DaysIcons.saturday_calendar_daily_page_interface_symbol,
                    audio: 'assets/audio/days_of_the_week/Bukas ay Sabado.mp3',
                    type: 'phrase'),
                LessonContent(
                    tagalogWord: 'Kahapon ay Martes',
                    engWord: 'Yesterday was Tuesday',
                    color: Colors.orange,
                    icon: DaysIcons
                        .tuesday_daily_calendar_page,
                    audio: 'assets/audio/days_of_the_week/Kahapon ay Martes.mp3',
                    type: 'phrase'),
                LessonContent(
                    tagalogWord: 'Ngayon ay Linggo',
                    engWord: 'Today is Sunday',
                    color: Colors.orange,
                    icon:DaysIcons.sunday_daily_calendar_page,
                    audio: 'assets/audio/days_of_the_week/Ngayon ay Linggo.mp3',
                    type: 'phrase'),
              ]),
          Lesson(
              name: 'Days Three',
              icon: FontAwesomeIcons.spaceShuttle,
              color: Colors.red[700],
              backgroundColor: Colors.redAccent,
              difficulty: 'Hard',
              lessonContent: [
                LessonContent(
                    tagalogWord: 'Ako ay magbabakasyon sa Martes',
                    engWord: 'I am going on holiday on Tuesday',
                    icon: FontAwesomeIcons.plane,
                    audio: 'assets/audio/days_of_the_week/Ako ay magbabakasyon sa Martes.mp3',
                    color: Colors.white,
                    type: 'phrase'),
                LessonContent(
                    tagalogWord: 'Magbabakasyon ako ng dalawang linggo',
                    engWord: 'I am going on holiday for 2 weeks',
                    icon: FontAwesomeIcons.plane,
                    audio:
                        'assets/audio/days_of_the_week/Magbabakasyon ako ng dalawang linggo.mp3',
                    color: Colors.white,
                    type: 'phrase'),
                LessonContent(
                    tagalogWord: 'Ano ang petsa ngayon?',
                    engWord: 'What is the date today',
                    icon: FontAwesomeIcons.plane,
                    audio: 'assets/audio/days_of_the_week/Ano ang petsa ngayon_.mp3',
                    color: Colors.white,
                    type: 'phrase'),
                LessonContent(
                    tagalogWord: 'Ang petsa ngayon ay...',
                    engWord: 'Today\'s date is...',
                    icon: FontAwesomeIcons.plane,
                    audio: 'assets/audio/days_of_the_week/Ang petsa ngayon ay.mp3',
                    color: Colors.white,
                    type: 'phrase'),
                LessonContent(
                    tagalogWord:
                        'Ang petsa ngayon ay dalawampu\'t-tatlo ng Agosto, 2021',
                    engWord: 'Today\'s date is 23rd of August, 2021',
                    icon: FontAwesomeIcons.plane,
                    audio:
                        'assets/audio/days_of_the_week/ang petsa ngayon ay dalawampu\'t-tatlo ng Agosto, 2021.mp3',
                    color: Colors.white,
                    type: 'phrase'),
              ]),
        ],
      ),
      Topic(
        name: 'Months',
        icon: FontAwesomeIcons.paintBrush,
        color: Colors.cyan,
        backgroundColor: Colors.cyanAccent,
        lessons: [
          Lesson(
              name: 'Months One',
              icon: FontAwesomeIcons.calendar,
              color: Colors.cyan,
              backgroundColor: Colors.cyanAccent,
              difficulty: 'Easy',
              lessonContent: [
                LessonContent(
                    tagalogWord: 'Enero',
                    engWord: 'January',
                    icon: MonthsIcon.jan,
                    audio: 'assets/audio/months/Enero.mp3',
                    color: Colors.white,
                    type: 'word'),
                LessonContent(
                    tagalogWord: 'Pebrero',
                    engWord: 'February',
                    icon: MonthsIcon.feb,
                    audio: 'assets/audio/months/Pebrero.mp3',
                    color: Colors.white,
                    type: 'word'),
                LessonContent(
                    tagalogWord: 'Marso',
                    engWord: 'March',
                    icon: MonthsIcon.mar,
                    audio: 'assets/audio/months/Marso.mp3',
                    color: Colors.white,
                    type: 'word'),
                LessonContent(
                    tagalogWord: 'Abril',
                    engWord: 'April',
                    icon: MonthsIcon.apr,
                    audio: 'assets/audio/months/Abril.mp3',
                    color: Colors.white,
                    type: 'word'),
                LessonContent(
                    tagalogWord: 'Mayo',
                    engWord: 'May',
                    icon: MonthsIcon.may,
                    audio: 'assets/audio/months/Mayo.mp3',
                    color: Colors.white,
                    type: 'word'),
                LessonContent(
                    tagalogWord: 'Hunyo',
                    engWord: 'June',
                    icon: MonthsIcon.jun,
                    audio: 'assets/audio/months/Hunyo.mp3',
                    color: Colors.white,
                    type: 'word'),
                LessonContent(
                    tagalogWord: 'Hulyo',
                    engWord: 'July',
                    icon: MonthsIcon.jul,
                    audio: 'assets/audio/months/Hulyo.mp3',
                    color: Colors.white,
                    type: 'word'),
                LessonContent(
                    tagalogWord: 'Agosto',
                    engWord: 'August',
                    icon: MonthsIcon.aug,
                    audio: 'assets/audio/months/Agosto.mp3',
                    color: Colors.white,
                    type: 'word'),
                LessonContent(
                    tagalogWord: 'Septiembre',
                    engWord: 'September',
                    icon:MonthsIcon.sep,
                    audio: 'assets/audio/months/Septiembre.mp3',
                    color: Colors.white,
                    type: 'word'),
                LessonContent(
                    tagalogWord: 'Oktubre',
                    engWord: 'October',
                    icon: MonthsIcon.oct,
                    audio: 'assets/audio/months/Oktubre.mp3',
                    color: Colors.white,
                    type: 'word'),
                LessonContent(
                    tagalogWord: 'Nobyembre',
                    engWord: 'November',
                    icon: MonthsIcon.nov,
                    audio: 'assets/audio/months/Nobyembre.mp3',
                    color: Colors.white,
                    type: 'word'),
                LessonContent(
                    tagalogWord: 'Disyembre',
                    engWord: 'Decemeber',
                    icon: MonthsIcon.dec,
                    audio: 'assets/audio/months/Disyembre.mp3',
                    color: Colors.white,
                    type: 'word'),
              ]),
          Lesson(
              name: 'Months Two',
              icon: FontAwesomeIcons.calendarDay,
              color: Colors.cyan,
              backgroundColor: Colors.cyanAccent,
              difficulty: 'Medium',
              lessonContent: [
                LessonContent(
                    tagalogWord: 'Kaarawan',
                    engWord: 'Birthday',
                    icon: FontAwesomeIcons.birthdayCake,
                    audio: 'assets/audio/months/Kaarawan.mp3',
                    color: Colors.white,
                    type: 'word'),
                LessonContent(
                    tagalogWord: 'Ang nanay ko ay ipinanganak noong Oktubre',
                    engWord: 'My mother was born in October',
                    icon: FontAwesomeIcons.birthdayCake,
                    audio:
                        'assets/audio/months/Ang nanay ko ay ipinanganak noong Oktubre.mp3',
                    color: Colors.white,
                    type: 'phrase'),
                LessonContent(
                    tagalogWord: 'Ang araw ng kapanganakan ko ay Enero',
                    engWord: 'My birthday is in January',
                    icon: FontAwesomeIcons.birthdayCake,
                    audio:
                        'assets/audio/months/Ang araw ng kapanganakan ko ay Enero.mp3',
                    color: Colors.white,
                    type: 'phrase'),
                LessonContent(
                    tagalogWord:
                        'Ang kapanganakan ng kapatid kong babae ay Marso',
                    engWord: 'My sisters birthday is on March',
                    icon: FontAwesomeIcons.birthdayCake,
                    audio:
                        'assets/audio/months/Ang kapanganakan ng kapatid kong babae ay Marso.mp3',
                    color: Colors.white,
                    type: 'phrase'),
                LessonContent(
                    tagalogWord:
                        'Ang kaarawan ng aking kapatid ay sa Setyembre',
                    engWord: 'My brothers birthday is on September',
                    icon: FontAwesomeIcons.birthdayCake,
                    audio:
                        'assets/audio/months/Ang kaarawan ng aking kapatid ay sa Setyembre.mp3',
                    color: Colors.white,
                    type: 'phrase'),
                LessonContent(
                    tagalogWord: 'Ang kaarawan ng aking tiyuhin ay sa Hulyo',
                    engWord: 'My uncles birthday is on July',
                    icon: FontAwesomeIcons.birthdayCake,
                    audio:
                        'assets/audio/months/Ang kaarawan ng aking tiyuhin ay sa Hulyo.mp3',
                    color: Colors.white,
                    type: 'phrase'),
                LessonContent(
                    tagalogWord: 'Ang kaarawan ng aking Tita ay sa Agosto',
                    engWord: 'My aunties birthday is on August',
                    icon: FontAwesomeIcons.birthdayCake,
                    audio:
                        'assets/audio/months/Ang kaarawan ng aking Tita ay sa Agosto.mp3',
                    color: Colors.white,
                    type: 'phrase'),
              ]),
          Lesson(
              name: 'Months Three',
              icon: FontAwesomeIcons.calendarWeek,
              color: Colors.cyan,
              backgroundColor: Colors.cyanAccent,
              difficulty: 'Hard',
              lessonContent: [
                LessonContent(
                    tagalogWord: 'Ang kaarawan ko ay ikalawa ng Enero',
                    engWord: 'My birthday is the 2nd of January',
                    icon: FontAwesomeIcons.birthdayCake,
                    audio:
                        'assets/audio/months/Ang kaarawan ko ay ikalawa ng Enero.mp3',
                    color: Colors.white,
                    type: 'phrase'),
                LessonContent(
                    tagalogWord:
                        'Ipinanganak ako noong ika-dalawampu\'t tatlo ng Marso dalawang libo at isa',
                    engWord: 'I was born on the 23rd of March',
                    icon: FontAwesomeIcons.birthdayCake,
                    audio:
                        'assets/audio/months/Ipinanganak ako noong ika-dalawampu\'t tatlo ng Marso dalawang libo at isa.mp3',
                    color: Colors.white,
                    type: 'phrase'),
                LessonContent(
                    tagalogWord:
                        'Ipinanganak ako noong ika-30, Mayo Labing-siyam walumpu',
                    engWord: 'I was born on the 30th, May 1980',
                    icon: FontAwesomeIcons.birthdayCake,
                    audio:
                        'assets/audio/months/Ipinanganak ako noong ika-30, Mayo Labing-siyam walumpu.mp3',
                    color: Colors.white,
                    type: 'phrase'),
                LessonContent(
                    tagalogWord: 'Ang aking kaarawan ay ikalabinsiyam ng june',
                    engWord: 'My birthday is the 19th of June',
                    icon: FontAwesomeIcons.birthdayCake,
                    audio:
                        'assets/audio/months/Ang aking kaarawan ay ikalabinsiyam ng june.mp3',
                    color: Colors.white,
                    type: 'phrase'),
                LessonContent(
                    tagalogWord:
                        'Ang kaarawan ng aking kapatid ay sa ikalabing-apat ng Nobyembre',
                    engWord: 'My brothers birthday is the 14th of November',
                    icon: FontAwesomeIcons.birthdayCake,
                    audio:
                        'assets/audio/months/ang kaarawan ng aking kapatid ay sa ikalabing-apat ng Nobyembre.mp3',
                    color: Colors.white,
                    type: 'phrase'),
                LessonContent(
                    tagalogWord:
                        'Ang kaarawan ng aking kapatid na babae ay ang dalawampu\'t segundo ng Pebrero',
                    engWord: 'My sisters birthday is the 22nd of Feburary',
                    icon: FontAwesomeIcons.birthdayCake,
                    audio:
                        'assets/audio/months/Ang kaarawan ng aking kapatid na babae ay ang dalawampu\'t segundo ng Pebrero.mp3',
                    color: Colors.white,
                    type: 'phrase'),
                LessonContent(
                    tagalogWord:
                        'Ang kaarawan ng pinsan ko ay pang-apat ng Mayo',
                    engWord: 'My cousins birthday is the 4th of May',
                    icon: FontAwesomeIcons.birthdayCake,
                    audio:
                        'assets/audio/months/Ang kaarawan ng pinsan ko ay pang-apat ng Mayo.mp3',
                    color: Colors.white,
                    type: 'phrase'),
              ]),
        ],
      ),
      Topic(
        name: 'Colours',
        icon: FontAwesomeIcons.paintBrush,
        color: Colors.deepOrange,
        backgroundColor: Colors.orangeAccent,
        lessons: [
          Lesson(
              name: 'Colours One',
              icon: FontAwesomeIcons.paintBrush,
              color: Colors.deepOrange,
              backgroundColor: Colors.orangeAccent,
              difficulty: 'Easy',
              lessonContent: [
                LessonContent(
                    tagalogWord: 'Puti',
                    engWord: 'White',
                    icon: Icons.circle,
                    color: Colors.white,
                    audio: 'assets/audio/colours/Puti.mp3',
                    type: 'word'),
                LessonContent(
                    tagalogWord: 'Itim',
                    engWord: 'Black',
                    icon: Icons.circle,
                    color: Colors.black,
                    audio: 'assets/audio/colours/itim.mp3',
                    type: 'word'),
                LessonContent(
                    tagalogWord: 'Bughan',
                    engWord: 'Blue',
                    icon: Icons.circle,
                    color: Colors.blue,
                    audio: 'assets/audio/colours/Bughan.mp3',
                    type: 'word'),
                LessonContent(
                    tagalogWord: 'Pula',
                    engWord: 'Red',
                    icon: Icons.circle,
                    color: Colors.red,
                    audio: 'assets/audio/colours/Pula.mp3',
                    type: 'word'),
                LessonContent(
                    tagalogWord: 'Kayumangi',
                    engWord: 'Brown',
                    icon: Icons.circle,
                    color: Colors.brown,
                    audio: 'assets/audio/colours/Kayumangi.mp3',
                    type: 'word'),
                LessonContent(
                    tagalogWord: 'Dilaw',
                    engWord: 'Yellow',
                    icon: Icons.circle,
                    color: Colors.yellow,
                    audio: 'assets/audio/colours/Dilaw.mp3',
                    type: 'word'),
              ]),
          Lesson(
              name: 'Colours Two',
              icon: FontAwesomeIcons.paintRoller,
              color: Colors.deepOrange,
              backgroundColor: Colors.orangeAccent,
              difficulty: 'Easy',
              lessonContent: [
                LessonContent(
                    tagalogWord: 'Violet',
                    engWord: 'Purple',
                    icon: Icons.circle,
                    color: Colors.purple,
                    audio: 'assets/audio/colours/Violet.mp3',
                    type: 'word'),
                LessonContent(
                    tagalogWord: 'Kulay',
                    engWord: 'Orange',
                    icon: Icons.circle,
                    color: Colors.orange,
                    audio: 'assets/audio/colours/Kulay.mp3',
                    type: 'word'),
                LessonContent(
                    tagalogWord: 'Abo',
                    engWord: 'Grey',
                    icon: Icons.circle,
                    color: Colors.grey,
                    audio: 'assets/audio/colours/Abo.mp3',
                    type: 'word'),
                LessonContent(
                    tagalogWord: 'Berde',
                    engWord: 'Green',
                    icon: Icons.circle,
                    color: Colors.green,
                    audio: 'assets/audio/colours/Berde.mp3',
                    type: 'word'),
              ]),
          Lesson(
              name: 'Colours Three',
              icon: FontAwesomeIcons.hatWizard,
              color: Colors.deepOrange,
              backgroundColor: Colors.orangeAccent,
              difficulty: 'Medium',
              lessonContent: [
                LessonContent(
                  tagalogWord: 'Pulang Sweater',
                  engWord: 'Red Jumper',
                  icon: FontAwesomeIcons.personBooth,
                  color: Colors.red,
                  audio: 'assets/audio/colours/Pulang Sweater.mp3',
                  type: 'phrase',
                ),
                LessonContent(
                  tagalogWord: 'Bughaw na sapatos',
                  engWord: 'Blue shoes',
                  icon: FontAwesomeIcons.shoePrints,
                  color: Colors.blue,
                  audio: 'assets/audio/colours/Bughaw na sapatos.mp3',
                  type: 'phrase',
                ),
                LessonContent(
                  tagalogWord: 'Berdeng Jacket',
                  engWord: 'Green Jacket',
                  icon: FontAwesomeIcons.personBooth,
                  color: Colors.green,
                  audio: 'assets/audio/colours/Berdeng Jacket.mp3',
                  type: 'phrase',
                ),
                LessonContent(
                  tagalogWord: 'Dilaw na balla',
                  engWord: 'Yellow Ball',
                  icon: FontAwesomeIcons.golfBall,
                  color: Colors.yellow,
                  audio: 'assets/audio/colours/Dilaw na balla.mp3',
                  type: 'phrase',
                ),
                LessonContent(
                  tagalogWord: 'Orange na sumbrero',
                  engWord: 'Orange hat',
                  icon: FontAwesomeIcons.hatCowboy,
                  color: Colors.orange,
                  audio: 'assets/audio/colours/Orange na sumbrero.mp3',
                  type: 'phrase',
                ),
              ]),
          Lesson(
              name: 'Colours Four',
              icon: FontAwesomeIcons.shoppingBag,
              color: Colors.deepOrange,
              backgroundColor: Colors.orangeAccent,
              difficulty: 'Medium',
              lessonContent: [
                LessonContent(
                  tagalogWord: 'Itim na sapatos',
                  engWord: 'Black shoes',
                  icon: FontAwesomeIcons.shoePrints,
                  color: Colors.black,
                  audio: 'assets/audio/colours/Itim na Sapatos.mp3',
                  type: 'phrase',
                ),
                LessonContent(
                  tagalogWord: 'Kayumanggi bag',
                  engWord: 'Brown bag',
                  icon: FontAwesomeIcons.shoppingBag,
                  color: Colors.brown,
                  audio: 'assets/audio/colours/Kayumanggi bag.mp3',
                  type: 'phrase',
                ),
                LessonContent(
                  tagalogWord: 'Orange na pusa',
                  engWord: 'Orange cat',
                  icon: FontAwesomeIcons.cat,
                  color: Colors.orange,
                  audio: 'assets/audio/colours/Orange na pusa.mp3',
                  type: 'phrase',
                ),
                LessonContent(
                  tagalogWord: 'Purple na medyas',
                  engWord: 'Purple socks',
                  icon: FontAwesomeIcons.socks,
                  color: Colors.deepPurple,
                  audio: 'assets/audio/colours/Purple na medyas.mp3',
                  type: 'phrase',
                ),
                LessonContent(
                  tagalogWord: 'Puting medyas',
                  engWord: 'White socks',
                  icon: FontAwesomeIcons.socks,
                  color: Colors.white,
                  audio: 'assets/audio/colours/Puting medyas.mp3',
                  type: 'phrase',
                ),
              ]),
          Lesson(
              name: 'Colours Five',
              icon: FontAwesomeIcons.tshirt,
              color: Colors.deepOrange,
              backgroundColor: Colors.orangeAccent,
              difficulty: 'Hard',
              lessonContent: [
                LessonContent(
                  tagalogWord: 'Suot ko ay asul na medyas',
                  engWord: 'I am wearing blue socks',
                  icon: FontAwesomeIcons.socks,
                  color: Colors.blue,
                  audio: 'assets/audio/colours/Suot ko ay asul na medyas.mp3',
                  type: 'phrase',
                ),
                LessonContent(
                  tagalogWord: 'Suot ko ay pulang sweater',
                  engWord: 'I am wearing a red jumper',
                  icon: Icons.person_rounded,
                  color: Colors.red,
                  audio: 'assets/audio/colours/Suot ko ay pulang sweater.mp3',
                  type: 'phrase',
                ),
                LessonContent(
                  tagalogWord: 'Suot ko ang orange na t-shirt',
                  engWord: 'I am wearing an orange t-shirt',
                  icon: FontAwesomeIcons.tshirt,
                  color: Colors.orange,
                  audio: 'assets/audio/colours/Suot ko an orange na t-shirt.mp3',
                  type: 'phrase',
                ),
                LessonContent(
                  tagalogWord: 'Suot ko ay berdeng sumbrero',
                  engWord: 'I am wearing a green hat',
                  icon: FontAwesomeIcons.hatWizard,
                  color: Colors.green,
                  audio: 'assets/audio/colours/Suot ko ay berdeng sumbrero.mp3',
                  type: 'phrase',
                ),
                LessonContent(
                  tagalogWord: 'Suot ko ay light blue sweater',
                  engWord: 'I am wearing a light blue jumper ',
                  icon: FontAwesomeIcons.personBooth,
                  color: Colors.lightBlue,
                  audio: 'assets/audio/colours/Suot ko ay light blue sweater.mp3',
                  type: 'phrase',
                ),
                LessonContent(
                  tagalogWord: 'Suot ko ay dark brown na saptos',
                  engWord: 'I am wearing dark brown shoes',
                  icon: FontAwesomeIcons.shoePrints,
                  color: Color(0xFF2B1D16),
                  audio: 'assets/audio/colours/Suot ko ay dark brown na saptos.mp3',
                  type: 'phrase',
                ),
                LessonContent(
                  tagalogWord: 'Suot ko ay grey na saptos',
                  engWord: 'I am wearing grey trainers',
                  icon: FontAwesomeIcons.hatWizard,
                  color: Color(0xFF2B1D16),
                  audio: 'assets/audio/colours/Suot ko ay grey na saptos.mp3',
                  type: 'phrase',
                ),
                LessonContent(
                  tagalogWord: 'Nakasuot ako ng puting medyas',
                  engWord: 'I am wearing white socks (Formal)',
                  icon: FontAwesomeIcons.hatWizard,
                  color: Color(0xFF2B1D16),
                  audio: 'assets/audio/colours/Nakasuot ako ng puting medyas.mp3',
                  type: 'phrase',
                ),
              ]),
          Lesson(
            name: 'Colours Six',
            icon: FontAwesomeIcons.suitcase,
            color: Colors.deepOrange,
            backgroundColor: Colors.orangeAccent,
            difficulty: 'Hard',
            lessonContent: [
              LessonContent(
                tagalogWord: 'Meron akong brown na bag',
                engWord: 'I have a brown bag',
                icon: FontAwesomeIcons.shoppingBag,
                color: Colors.brown,
                audio: 'assets/audio/colours/Meron akong brown na bag.mp3',
                type: 'phrase',
              ),
              LessonContent(
                tagalogWord: 'Meron akong purple na malleta',
                engWord: 'I have a purple suitcase',
                icon: FontAwesomeIcons.suitcase,
                color: Colors.purple,
                audio: 'assets/audio/colours/Meron akong purple na malleta.mp3',
                type: 'phrase',
              ),
              LessonContent(
                tagalogWord: 'Meron akong orange na pusa',
                engWord: 'I have an orange cat',
                icon: FontAwesomeIcons.cat,
                color: Colors.orange,
                audio: 'assets/audio/colours/Meron akong orange na pusa.mp3',
                type: 'phrase',
              ),
              LessonContent(
                tagalogWord: 'Meron akong bag na kulay dilaw',
                engWord: 'I have a yellow bag',
                icon: Icons.shopping_bag,
                color: Colors.yellow,
                audio: 'assets/audio/colours/Meron akong bag na kulay dilaw.mp3',
                type: 'phrase',
              ),
              LessonContent(
                tagalogWord: 'Mayroon akong mga bulaklak na kahel',
                engWord: 'I have orange flowers',
                icon: Icons.filter_vintage,
                color: Colors.orange,
                audio: 'assets/audio/colours/Mayroon akong mga bulaklak na kahel.mp3',
                type: 'phrase',
              ),
              LessonContent(
                tagalogWord: 'Siya ay may ilaw na berde na mga mata',
                engWord: 'She has light green eyes',
                icon: FontAwesomeIcons.eye,
                color: Colors.green,
                audio: 'assets/audio/colours/Siya ay may ilaw na berde na mga mata.mp3',
                type: 'phrase',
              ),
            ],
          ),
        ],
      ),
    ];
  } 
}
