/// Flutter icons AlphabetLetters
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AlphabetLetters
///      fonts:
///       - asset: fonts/AlphabetLetters.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class AlphabetLetters {
  AlphabetLetters._();

  static const _kFontFam = 'AlphabetLetters';
  static const String _kFontPkg = null;

  static const IconData alpha_y = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alpha_w = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alpha_v = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alpha_u = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alpha_t = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alpha_s = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alpha_r = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alpha_p = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alpha_o = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alpha_n = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alpha_m = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alpha_l = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alpha_i = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alpha_h = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alpha_g = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alpha_e = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alpha_d = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alpha_c = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alpha_b = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alpha_a = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
