/// Flutter icons DaysIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  DaysIcons
///      fonts:
///       - asset: fonts/DaysIcons.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
///
import 'package:flutter/widgets.dart';

class DaysIcons {
  DaysIcons._();

  static const _kFontFam = 'DaysIcons';
  static const String _kFontPkg = null;

  static const IconData monday_calendar_page = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sunday_daily_calendar_page = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData saturday_calendar_daily_page_interface_symbol = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData friday_daily_calendar_page = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thursday_calendar_daily_page_interface_symbol = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wednesday_calendar_daily_page = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tuesday_daily_calendar_page = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData view_week = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
