/// Flutter icons MonthsIcon
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MonthsIcon
///      fonts:
///       - asset: fonts/MonthsIcon.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
///
import 'package:flutter/widgets.dart';

class MonthsIcon {
  MonthsIcon._();

  static const _kFontFam = 'MonthsIcon';
  static const String _kFontPkg = null;

  static const IconData jan = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData feb = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mar = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData apr = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData may = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData jun = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData jul = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData aug = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sep = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData oct_1 = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dec = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData nov = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData oct = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData view_week = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
