/// Flutter icons NumberIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  NumberIcons
///      fonts:
///       - asset: fonts/NumberIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class NumberIcons {
  NumberIcons._();

  static const _kFontFam = 'NumberIcons';
  static const String _kFontPkg = null;

  static const IconData twenty = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thirty = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData forty = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fifty = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sixty = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eighty = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ninety = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData birthday = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
